In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv(r"C:\Users\hp\LOAN_DEFAULT_ANALYSIS\Cleaned_csv_file\Loan_default_clean.csv")

C:\Users\hp\AppData\Local\Temp\ipykernel_8544\4216590154.py:4: DtypeWarning: Columns (0: next_pymnt_d) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\hp\LOAN_DEFAULT_ANALYSIS\Cleaned_csv_file\Loan_default_clean.csv")

In [2]:
finalized_loans = df[
    df["default_status"].isin(
        ["Defaulted", "Did Not Default"]
    )
].copy()

Grade + term

In [3]:
grade_term_default = pd.crosstab(
    [
        finalized_loans["grade"],
        finalized_loans["term"]
    ],
    finalized_loans["default_status"],
    normalize="index"
) * 100

grade_term_default

default_status   Defaulted  Did Not Default
grade term
A     36 months   5.966586        94.033414
      60 months  10.472074        89.527926
B     36 months  12.807251        87.192749
      60 months  18.098839        81.901161
C     36 months  20.601830        79.398170
      60 months  27.532938        72.467062
D     36 months  26.962485        73.037515
      60 months  36.334091        63.665909
E     36 months  32.831834        67.168166
      60 months  42.176835        57.823165
F     36 months  38.307713        61.692287
      60 months  47.340142        52.659858
G     36 months  47.026364        52.973636
      60 months  50.399255        49.600745

In [4]:
grade_term_default["Defaulted"]

grade  term
A      36 months     5.966586
       60 months    10.472074
B      36 months    12.807251
       60 months    18.098839
C      36 months    20.601830
       60 months    27.532938
D      36 months    26.962485
       60 months    36.334091
E      36 months    32.831834
       60 months    42.176835
F      36 months    38.307713
       60 months    47.340142
G      36 months    47.026364
       60 months    50.399255
Name: Defaulted, dtype: float64

Interest rate groups

In [5]:
df["interest_rate_group"] = pd.cut(
    df["int_rate"],
    bins=[0, 5, 10, 15, 20, 25, 100],
    labels=[
        "0-5%",
        "5-10%",
        "10-15%",
        "15-20%",
        "20-25%",
        "25%+"
    ]
)

In [6]:
finalized_loans_interest = df[
    df["default_status"].isin(
        ["Defaulted", "Did Not Default"]
    )
].copy()

In [8]:
interest_default = pd.crosstab(
    finalized_loans_interest["interest_rate_group"],
    finalized_loans["default_status"],
    normalize="index"
) * 100

interest_default

default_status       Defaulted  Did Not Default
interest_rate_group
5-10%                 8.235616        91.764384
10-15%               18.680946        81.319054
15-20%               29.671545        70.328455
20-25%               38.631428        61.368572
25%+                 47.865914        52.134086

DTI groups

In [9]:
df["dti_group"] = pd.cut(
    df["dti"],
    bins=[-1, 10, 20, 30, 40, 100],
    labels=[
        "0-10",
        "10-20",
        "20-30",
        "30-40",
        "40+"
    ]
)

In [10]:
finalized_loans_dti= df[
    df["default_status"].isin(
        ["Defaulted", "Did Not Default"]
    )
].copy()

In [11]:
dti_default = pd.crosstab(
    finalized_loans_dti["dti_group"],
    finalized_loans_dti["default_status"],
    normalize="index"
) * 100

dti_default

default_status  Defaulted  Did Not Default
dti_group
0-10            14.916885        85.083115
10-20           17.967066        82.032934
20-30           23.200488        76.799512
30-40           29.403096        70.596904
40+             32.212736        67.787264

Income groups

In [12]:
df["income_group"] = pd.qcut(
    df["annual_inc"],
    q=4,
    labels=[
        "Low Income",
        "Lower-Middle Income",
        "Upper-Middle Income",
        "High Income"
    ],
    duplicates="drop"
)

In [13]:
finalized_loans_income= df[
    df["default_status"].isin(
        ["Defaulted", "Did Not Default"]
    )
].copy()

In [14]:
income_default = pd.crosstab(
finalized_loans_income["income_group"],
finalized_loans_income["default_status"],
    normalize="index"
) * 100

income_default

default_status       Defaulted  Did Not Default
income_group
Low Income           23.412874        76.587126
Lower-Middle Income  21.244534        78.755466
Upper-Middle Income  19.066629        80.933371
High Income          16.249817        83.750183

Grade + interest rate

In [15]:
grade_interest_default = pd.crosstab(
    [
        finalized_loans_interest["grade"],
        finalized_loans_interest["interest_rate_group"]
    ],
    finalized_loans_interest["default_status"],
    normalize="index"
) * 100

grade_interest_default["Defaulted"]

grade  interest_rate_group
A      5-10%                   6.086338
B      5-10%                  11.833379
       10-15%                 14.337089
C      5-10%                   7.758621
       10-15%                 22.308190
       15-20%                 23.286817
D      5-10%                   3.797468
       10-15%                 20.396745
       15-20%                 30.481903
       20-25%                 31.749352
E      5-10%                   5.555556
       10-15%                 31.046931
       15-20%                 39.004249
       20-25%                 37.993219
       25%+                   40.593062
F      5-10%                  36.363636
       15-20%                 30.086313
       20-25%                 43.492818
       25%+                   49.961173
G      5-10%                  20.000000
       15-20%                 36.477987
       20-25%                 37.541528
       25%+                   51.448378
Name: Defaulted, dtype: float64

Filtering to columns needed for default analysis

In [43]:
default_analysis_columns = [
    # Outcome
    "default_status",

    # Loan characteristics
    "loan_amnt",
    "term",
    "int_rate",
    "installment",
    "grade",
    "sub_grade",
    "purpose",

    # Borrower characteristics
    "annual_inc",
    "emp_length",
    "home_ownership",
    "verification_status",
    "dti",

    # Credit history
    "delinq_2yrs",
    "inq_last_6mths",
    "mths_since_last_delinq",
    "open_acc",
    "pub_rec",
    "revol_util",
    "total_acc",
    "pub_rec_bankruptcies",

    # Credit/debt indicators
    "revol_bal",
    "tot_cur_bal",
    "avg_cur_bal",
    "bc_util",
    "total_rev_hi_lim",
    "collections_12_mths_ex_med",
    "chargeoff_within_12_mths",
    "acc_now_delinq",
    "num_accts_ever_120_pd",
    "pct_tl_nvr_dlq",
    'interest_rate_group',
    'dti_group',
    'income_group',

    # Time
    "issue_d"
]

In [44]:
default_analysis = finalized_loans_income[default_analysis_columns].copy()

In [45]:
default_analysis

,default_status,loan_amnt,term,int_rate,installment,grade,sub_grade,purpose,annual_inc,emp_length,...,total_rev_hi_lim,collections_12_mths_ex_med,chargeoff_within_12_mths,acc_now_delinq,num_accts_ever_120_pd,pct_tl_nvr_dlq,interest_rate_group,dti_group,income_group,issue_d
100,Did Not Default,30000,36 months,22.35,1151.16,D,D5,debt_consolidation,100000.0,5 years,...,42200.0,0.0,0.0,0.0,0.0,89.5,20-25%,30-40,High Income,Dec-2018
152,Did Not Default,40000,60 months,16.14,975.71,C,C4,credit_card,45000.0,< 1 year,...,54200.0,0.0,0.0,0.0,0.0,100.0,15-20%,40+,Low Income,Dec-2018
170,Did Not Default,20000,36 months,7.56,622.68,A,A3,credit_card,100000.0,10+ years,...,85100.0,0.0,0.0,0.0,0.0,94.7,5-10%,10-20,High Income,Dec-2018
186,Did Not Default,4500,36 months,11.31,147.99,B,B3,credit_card,38500.0,10+ years,...,29200.0,0.0,0.0,0.0,1.0,91.7,10-15%,0-10,Low Income,Dec-2018
215,Did Not Default,8425,36 months,27.27,345.18,E,E5,credit_card,450000.0,3 years,...,56000.0,0.0,0.0,0.0,0.0,100.0,25%+,10-20,High Income,Dec-2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260654,Defaulted,30000,60 months,17.09,747.03,D,D1,debt_consolidation,80000.0,2 years,...,62400.0,0.0,0.0,0.0,22.0,54.9,15-20%,20-30,Upper-Middle Income,Oct-2017
2260655,Defaulted,18000,60 months,30.65,589.57,F,F4,debt_consolidation,77000.0,10+ years,...,22400.0,0.0,0.0,0.0,0.0,93.3,25%+,0-10,Upper-Middle Income,Oct-2017
2260656,Did Not Default,17950,60 months,30.17,582.62,F,F3,debt_consolidation,53758.0,10+ years,...,16600.0,0.0,0.0,0.0,0.0,100.0,25%+,30-40,Lower-Middle Income,Oct-2017
2260658,Did Not Default,15000,60 months,16.02,364.94,C,C5,debt_consolidation,85000.0,< 1 year,...,28200.0,0.0,0.0,0.0,7.0,89.0,15-20%,10-20,Upper-Middle Income,Oct-2017
2260664,Did Not Default,12000,60 months,25.82,358.01,E,E4,debt_consolidation,30000.0,< 1 year,...,17300.0,0.0,0.0,0.0,2.0,76.9,25%+,10-20,Low Income,Oct-2017

In [47]:
default_analysis.to_csv("default_analysis_filtered.csv",index = False)

In [48]:
default_analysis.shape

(1306387, 35)

In [49]:
default_analysis.columns

Index(['default_status', 'loan_amnt', 'term', 'int_rate', 'installment',
       'grade', 'sub_grade', 'purpose', 'annual_inc', 'emp_length',
       'home_ownership', 'verification_status', 'dti', 'delinq_2yrs',
       'inq_last_6mths', 'mths_since_last_delinq', 'open_acc', 'pub_rec',
       'revol_util', 'total_acc', 'pub_rec_bankruptcies', 'revol_bal',
       'tot_cur_bal', 'avg_cur_bal', 'bc_util', 'total_rev_hi_lim',
       'collections_12_mths_ex_med', 'chargeoff_within_12_mths',
       'acc_now_delinq', 'num_accts_ever_120_pd', 'pct_tl_nvr_dlq',
       'interest_rate_group', 'dti_group', 'income_group', 'issue_d'],
      dtype='str')

In [50]:
default_analysis.head(5)

,default_status,loan_amnt,term,int_rate,installment,grade,sub_grade,purpose,annual_inc,emp_length,...,total_rev_hi_lim,collections_12_mths_ex_med,chargeoff_within_12_mths,acc_now_delinq,num_accts_ever_120_pd,pct_tl_nvr_dlq,interest_rate_group,dti_group,income_group,issue_d
100,Did Not Default,30000,36 months,22.35,1151.16,D,D5,debt_consolidation,100000.0,5 years,...,42200.0,0.0,0.0,0.0,0.0,89.5,20-25%,30-40,High Income,Dec-2018
152,Did Not Default,40000,60 months,16.14,975.71,C,C4,credit_card,45000.0,< 1 year,...,54200.0,0.0,0.0,0.0,0.0,100.0,15-20%,40+,Low Income,Dec-2018
170,Did Not Default,20000,36 months,7.56,622.68,A,A3,credit_card,100000.0,10+ years,...,85100.0,0.0,0.0,0.0,0.0,94.7,5-10%,10-20,High Income,Dec-2018
186,Did Not Default,4500,36 months,11.31,147.99,B,B3,credit_card,38500.0,10+ years,...,29200.0,0.0,0.0,0.0,1.0,91.7,10-15%,0-10,Low Income,Dec-2018
215,Did Not Default,8425,36 months,27.27,345.18,E,E5,credit_card,450000.0,3 years,...,56000.0,0.0,0.0,0.0,0.0,100.0,25%+,10-20,High Income,Dec-2018

In [54]:
default_analysis["loan_amnt"].max()

np.int64(40000)

In [59]:
default_analysis["annual_inc"].max()

np.float64(10999200.0)

In [60]:
default_analysis["annual_inc"].sort_values(ascending=False).head(20)

1458483    10999200.0
714651      9550000.0
1381011     9522972.0
1160644     9500000.0
284499      9300000.0
681275      9225000.0
970097      9000000.0
1147034     8900060.0
1330429     8706582.0
954058      8700000.0
977645      8500021.0
554941      8400000.0
1415911     8300000.0
1015700     8253000.0
1058542     8121180.0
1062443     7600000.0
1958412     7500000.0
2085147     7446395.0
2237694     7200000.0
1810381     7141778.0
Name: annual_inc, dtype: float64

In [61]:
pd.cut(
    default_analysis["annual_inc"],
    bins=[0, 25000, 50000, 75000, 100000, float("inf")],
    labels=["Under $25K", "$25K–$50K", "$50K–$75K", "$75K–$100K", "$100K+"]
).value_counts().sort_index()

annual_inc
Under $25K     49601
$25K–$50K     370869
$50K–$75K     400516
$75K–$100K    243170
$100K+        241925
Name: count, dtype: int64